// scripts/seed-bunny.ts
import { db } from '../src/server/db';
import { courses, chapters, lessons, transcripts } from '../src/server/db/schema';
import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query: string): Promise<string> => {
  return new Promise((resolve) => rl.question(query, resolve));
};

async function main() {
  console.log('🌱 開始建立種子資料...');

  // 1. 輸入資料
  const courseTitle = await question('請輸入課程名稱 (預設: GenAI Fundamentals): ') || 'GenAI Fundamentals';
  const videoId = await question('請輸入 Bunny Video ID: ');
  const transcriptText = await question('請貼上 TurboScribe 逐字稿內容 (單行或簡單測試用): ');

  if (!videoId) {
    console.error('❌ 錯誤: 必須提供 Video ID');
    process.exit(1);
  }

  // 2. 寫入資料庫
  console.log('📦 正在寫入資料庫...');
  
  // 建立課程
  const course = await db.insert(courses).values({
    title: courseTitle,
    description: 'Generated by Seed Script',
  }).returning().get();

  // 建立章節
  const chapter = await db.insert(chapters).values({
    courseId: course.id,
    title: 'Chapter 1: Getting Started',
    order: 1,
  }).returning().get();

  // 建立單元
  const lesson = await db.insert(lessons).values({
    chapterId: chapter.id,
    title: 'First Lesson',
    description: 'Deep dive into AI',
    videoId: videoId,
    duration: 120, // 假設值
    order: 1,
  }).returning().get();

  // 建立逐字稿 (這裡做一個簡單的模擬切割)
  // 實際 TurboScribe 會有時間戳，這裡我們先塞一條測試
  await db.insert(transcripts).values({
    lessonId: lesson.id,
    startTime: 0,
    endTime: 10,
    text: transcriptText || 'Welcome to this course.',
    order: 1,
  });

  console.log(`✅ 完成！課程 ID: ${course.id}, 單元 ID: ${lesson.id}`);
  rl.close();
}

main().catch(console.error);